version: '3.9'
services:
  medialist-next:
    container_name: MediaList-Web
    build: ./client
    ports:
      - "${WEB_PORT}:3000"
    restart: unless-stopped
    environment:
      API_URL: http://localhost:${SERVER_PORT}
    depends_on:
      - db
      - medialist-express
  medialist-express:
    container_name: MediaList-Server
    build: ./server
    ports:
      - "${SERVER_PORT}:3001"
    restart: unless-stopped
    environment:
      PORT: 3001
      NODE_ENV: production
      USING_HTTPS: false # For security reasons, set to true only if you are using HTTPS, it won't make the app use HTTPS
      ORIGIN_WHITELIST: http://localhost:${WEB_PORT},http://medialist-next:3000
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=${DB_SCHEMA}
    depends_on:
      - db
    volumes:
      - ./volumes/users:/app/public/users
  # If using a saperate database container:
  # - comment 'db' 
  # - removes the 'depends_on' from 'medialist-express' and 'medialist-next':
  db:
    container_name: MediaList-Database
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 4002:5432
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
